// <auto-generated />
using Lesson19_1.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lesson19_1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200404085827_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Lesson19_1.DataModels.BrandData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("BrandData");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Description = "For photos",
                            Name = "Cenon"
                        });
                });

            modelBuilder.Entity("Lesson19_1.DataModels.ModelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BrandDataId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("BrandDataId");

                    b.ToTable("ModelData");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            BrandDataId = 3,
                            Name = "G30"
                        });
                });

            modelBuilder.Entity("Lesson19_1.DataModels.ModelData", b =>
                {
                    b.HasOne("Lesson19_1.DataModels.BrandData", "BrandData")
                        .WithMany()
                        .HasForeignKey("BrandDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
